### ISSUE TITLE
AppCrawler version 2.1.3 运行时报错

### ISSUE THREAD

**Issue by sosocgx** [seveniruby/AppCrawler#13]
运行时报错，请问怎么解决？

2018-05-11 17:01:24 INFO [Crawler.start.141] waiting for app load
2018-05-11 17:01:32 INFO [Crawler.start.143] driver=null
2018-05-11 17:01:32 INFO [Crawler.start.144] get screen info
2018-05-11 17:01:32 INFO [AppiumClient.getDeviceInfo.217] screenWidth=1920 screenHeight=1128
2018-05-11 17:01:32 INFO [Crawler.refreshPage.554] refresh page
2018-05-11 17:01:32 INFO [AppiumClient.getPageSource.308] start to get page source from appium
2018-05-11 17:01:32 INFO [AppiumClient.$anonfun$getPageSource$1.321] xml format 
Exception in thread "main" java.lang.NoSuchMethodError: com.sun.org.apache.xml.internal.serialize.OutputFormat.(Lorg/w3c/dom/Document;)V
at com.testerhome.appcrawler.XPathUtil$.toPrettyXML(XPathUtil.scala:35)
at com.testerhome.appcrawler.driver.AppiumClient.$anonfun$getPageSource$1(AppiumClient.scala:336)
at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
at com.testerhome.appcrawler.driver.AppiumClient.getPageSource(AppiumClient.scala:310)
at com.testerhome.appcrawler.Crawler.refreshPage(Crawler.scala:555)
at com.testerhome.appcrawler.Crawler.start(Crawler.scala:146)
at com.testerhome.appcrawler.AppCrawler$.startCrawl(AppCrawler.scala:344)
at com.testerhome.appcrawler.AppCrawler$.parseParams(AppCrawler.scala:312)
at com.testerhome.appcrawler.AppCrawler$.main(AppCrawler.scala:92)
at com.testerhome.appcrawler.AppCrawler.main(AppCrawler.scala)

**Comment by benchenglian** [comment]
你看看配置文件，还有你描述一下你要做什么？
另外这个是启动app报错。还是运行到那步报错呢？可以结合配置文件和步骤，定位一下。

**Comment by benchenglian** [comment]
你看看配置文件，还有你描述一下你要做什么？这个是启动app报错。还是

**Comment by gitbbsun** [comment]
用2.4.0版本试一下

**Comment by silencewy** [comment]
> 用2.4.0版本试一下

2.4.0版本也有相同的问题

**Comment by Scarlett-m** [comment]
我用appcrawler-2.4.0-jar-with-dependencies.jar 运行了下，解决了你这个问题，可以试试
